name: build
on:
  pull_request: 
    types: [opened,synchronize,reopened]
    paths: ['src/**',.github/workflows/*]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**',.github/workflows/*]
jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd ## v6.0.2
    - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 ## v2.1.2
    - run: bun install
    - run: bun test
    - run: bun run --if-present predeploy
    - name: Upload artifact
      if: github.ref  == 'refs/heads/main'
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b ##v4.0.0
      with:
        path: dist/
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    if: github.ref  == 'refs/heads/main'
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e ##v4.0.5